# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_last_bd_srag_csv_url": "00_srag_data.ipynb",
         "get_srag_data": "00_srag_data.ipynb",
         "get_cities_states_dictionaries": "00_srag_data.ipynb",
         "treat_srag_data": "00_srag_data.ipynb"}

modules = ["srag_data.py"]

doc_url = "https://victor-marchesini.github.io/srag_data/"

git_url = "https://github.com/victor-marchesini/srag_data/tree/master/"

def custom_doc_links(name): return None
